FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY orders_main.py .

EXPOSE 8000

CMD ["uvicorn", "orders_main:app", "--host", "0.0.0.0", "--port", "8000"]
